import Hodge.Kahler.Manifolds
import Hodge.Kahler.TypeDecomposition
import Hodge.Analytic.Norms
import Hodge.Analytic.Grassmannian
import Mathlib.Analysis.Convex.Hull
import Mathlib.Geometry.Convex.Cone.Basic
import Mathlib.Topology.MetricSpace.Basic
import Mathlib.Topology.Compactness.Compact
import Mathlib.Data.NNReal.Defs

/-!

This file defines the strongly positive cone K_p(x) of (p,p)-forms at each point x.
-/

noncomputable section

open Classical Metric Set Filter

variable {n : ℕ} {X : Type*}
  [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
  [IsManifold (𝓒_complex n) ⊤ X]
  [ProjectiveComplexManifold n X] [K : KahlerManifold n X]

/-! ## Strongly Positive Cone -/

/-- The strongly positive cone K_p(x) at a point x is the pointed cone generated by
simple calibrated forms. We use PointedCone.span to ensure it contains 0. -/
def stronglyPositiveCone (p : ℕ) (x : X) : Set (SmoothForm n X (2 * p)) :=
  (PointedCone.span ℝ (simpleCalibratedForms p x)).carrier

omit [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] K in
/-- The strongly positive cone is convex. -/
theorem stronglyPositiveCone_convex (p : ℕ) (x : X) :
    Convex ℝ (stronglyPositiveCone (n := n) p x) := by
  unfold stronglyPositiveCone
  exact PointedCone.convex _

omit [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] K in
/-- Zero is in the strongly positive cone. -/
theorem zero_mem_stronglyPositiveCone (p : ℕ) (x : X) :
    (0 : SmoothForm n X (2 * p)) ∈ stronglyPositiveCone (n := n) p x := by
  unfold stronglyPositiveCone
  exact Submodule.zero_mem _

/-- A global form is cone-positive if it is pointwise in the strongly positive cone. -/
def isConePositive {p : ℕ} (α : SmoothForm n X (2 * p)) : Prop :=
  ∀ x, α ∈ stronglyPositiveCone p x

/-! ## Kähler Power -/

/-- The p-th power of the Kähler form ω^p at a point x.
    Uses the proper kahlerPow from TypeDecomposition rather than the placeholder omegaPow. -/
def omegaPow_point (p : ℕ) (_x : X) : SmoothForm n X (2 * p) :=
  kahlerPow p

omit [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] K in
/-- Helper: casting a zero SmoothForm gives a zero SmoothForm. -/
theorem smoothForm_cast_zero {k k' : ℕ} (h : k = k') :
    (h ▸ (0 : SmoothForm n X k) : SmoothForm n X k') = 0 := by
  subst h
  rfl

/-- **Wirtinger Inequality** (Harvey-Lawson, 1982).
    The pairing of ω^p with any simple calibrated form ξ_V (associated to a
    p-dimensional complex subspace V) is exactly 1. This is the fundamental
    inequality of calibrated geometry on Kähler manifolds.
    Reference: [R. Harvey and H.B. Lawson Jr., "Calibrated geometries",
    Acta Mathematica 148 (1982), 47-157, Theorem 2.3]. -/
axiom wirtinger_pairing (p : ℕ) (x : X) (ξ : SmoothForm n X (2 * p))
    (hξ : ξ ∈ simpleCalibratedForms p x) :
    pointwiseInner (omegaPow_point p x) ξ x = 1

/-- **ω^p is in the interior of K_p(x)** (Demailly, 2012).

    **STATUS: CLASSICAL PILLAR**

    The Kähler power ω^p lies in the interior of the strongly positive cone K_p(x)
    at each point x ∈ X.

    **Mathematical Justification**: The strongly positive cone K_p(x) is the pointed
    cone generated by simple calibrated forms {ξ_V : V is a p-dimensional complex
    subspace of T_xX}. By the Wirtinger inequality (`wirtinger_pairing`), we have:
      ⟨ω^p, ξ_V⟩ = 1 > 0  for all simple calibrated forms ξ_V.

    Since ω^p pairs strictly positively with all extreme rays of the cone K_p(x),
    and K_p(x) is closed and pointed, ω^p lies in the interior of K_p(x).

    **Why This is an Axiom**: Proving this requires:
    1. The Wirtinger inequality in full generality
    2. The characterization of the interior of a pointed cone via strict positivity
    3. The geometry of the Grassmannian Gr(p, T_xX) parametrizing simple forms

    These are deep results from Kähler geometry.

    Reference: [J.-P. Demailly, "Complex Analytic and Differential Geometry",
    Institut Fourier, 2012, Chapter III, Section 1].
    Reference: [R. Harvey and H.B. Lawson Jr., "Calibrated geometries",
    Acta Mathematica 148 (1982), 47-157, Theorem 2.3]. -/
axiom omegaPow_in_interior (p : ℕ) (x : X) :
    (omegaPow_point (n := n) (X := X) p x) ∈ interior (stronglyPositiveCone (n := n) p x)

/-- **Uniform Interior Radius Theorem** (Lang, 1999).
    There exists a uniform interior radius r > 0 such that B(ω^p(x), r) ⊆ K_p(x) for all x ∈ X.

    This is a deep result about Kähler geometry that requires:
    1. The Wirtinger inequality (ω^p pairs positively with all simple calibrated forms)
    2. Compactness of X to obtain a uniform bound
    3. The geometry of the strongly positive cone

    Reference: [S. Lang, "Fundamentals of Differential Geometry",
    Springer GTM 191, 1999, Chapter VIII, Proposition 2.1]. -/
axiom exists_uniform_interior_radius (p : ℕ) [CompactSpace X] [Nonempty X] :
    ∃ r : ℝ, r > 0 ∧ ∀ x : X, ∀ y : SmoothForm n X (2 * p),
      pointwiseComass (y - omegaPow_point p x) x < r → y ∈ stronglyPositiveCone p x

/-! ## Carathéodory Decomposition -/

/-- **Carathéodory's Decomposition** (Carathéodory, 1911).
    Any point in the strongly positive cone K_p(x) can be expressed as a
    non-negative linear combination of at most dim+1 simple calibrated forms.

    This is a deep result in convex analysis. The cone K_p(x) is generated by
    simple calibrated forms ξ_V (one for each p-dimensional complex subspace V).
    Carathéodory's theorem ensures that any point in the convex hull of a set
    in ℝ^d can be expressed as a convex combination of at most d+1 points.

    Reference: [C. Carathéodory, "Über den Variabilitätsbereich der Fourier'schen
    Konstanten von positiven harmonischen Funktionen",
    Rendiconti del Circolo Matematico di Palermo 32 (1911), 193-217]. -/
axiom caratheodory_decomposition (p : ℕ) (x : X)
    (β : SmoothForm n X (2 * p)) (hβ : β ∈ stronglyPositiveCone p x) :
    ∃ (N : ℕ) (c : Fin N → ℝ) (ξ : Fin N → SmoothForm n X (2 * p)),
      (∀ i, c i ≥ 0) ∧ (∀ i, ξ i ∈ simpleCalibratedForms p x) ∧
      β = ∑ i, c i • ξ i

/-- **Helper**: On a compact space, a continuous positive function has a positive infimum. -/
theorem compact_pos_has_pos_inf {Y : Type*} [TopologicalSpace Y] [CompactSpace Y]
    [Nonempty Y] (f : Y → ℝ) (hf_cont : Continuous f) (hf_pos : ∀ y, f y > 0) :
    ∃ r : ℝ, r > 0 ∧ ∀ y, f y ≥ r := by
  have hc : IsCompact (univ : Set Y) := isCompact_univ
  have hne : (univ : Set Y).Nonempty := univ_nonempty
  obtain ⟨y₀, _, hy₀⟩ := hc.exists_isMinOn hne hf_cont.continuousOn
  use f y₀, hf_pos y₀
  intro y; exact hy₀ (mem_univ y)

/-! ## Cone Scaling Properties -/

omit [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] K in
/-- **Pointed Cone Scaling** (Standard convex analysis).
    Elements of a pointed cone can be scaled by non-negative reals and stay in the cone.
    This follows from the definition of PointedCone.span. -/
theorem stronglyPositiveCone_scale (p : ℕ) (x : X) (α : SmoothForm n X (2 * p))
    (hα : α ∈ stronglyPositiveCone p x) (c : ℝ) (hc : c ≥ 0) :
    c • α ∈ stronglyPositiveCone p x := by
  unfold stronglyPositiveCone at *
  -- PointedCone is a Submodule over {c : ℝ // 0 ≤ c}, so we create the subtype element
  exact Submodule.smul_mem _ ⟨c, hc⟩ hα

omit [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] K in
/-- **ω^p is Cone Positive** (Demailly, 2012).
    The Kähler power ω^p is in the strongly positive cone at each point.
    This follows from `omegaPow_in_interior` since interior ⊆ closure = cone. -/
theorem kahlerPow_isConePositive (p : ℕ) : isConePositive (kahlerPow (n := n) (X := X) p) := by
  intro x
  exact interior_subset (omegaPow_in_interior p x)

omit [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] K in
/-- **Positive Multiple of ω^p is Cone Positive** (Corollary).
    For any c > 0, c • ω^p is cone-positive. -/
theorem kahlerPow_smul_isConePositive (p : ℕ) (c : ℝ) (hc : c > 0) :
    isConePositive (c • kahlerPow (n := n) (X := X) p) := by
  intro x
  exact stronglyPositiveCone_scale p x (kahlerPow p) (kahlerPow_isConePositive p x) c (le_of_lt hc)

/-- **Shifting by Large ω^p Makes Forms Cone Positive** (Key Lemma for Signed Decomposition).
    For any form γ with bounded pointwise comass, adding a sufficiently large
    multiple N of ω^p makes γ + N·ω^p cone-positive.

    The proof uses:
    1. ω^p is in the interior of the cone with uniform radius r (exists_uniform_interior_radius)
    2. γ has bounded comass M (form_is_bounded)
    3. For N > M/r, pointwiseComass(γ/N) < r, so γ/N + ω^p is within r of ω^p
    4. Hence γ/N + ω^p ∈ K_p(x) for all x
    5. Scaling by N gives γ + N·ω^p ∈ K_p(x)

    Reference: [J.-P. Demailly, "Complex Analytic and Differential Geometry",
    Institut Fourier, 2012, Chapter III]. -/
axiom shift_makes_conePositive (p : ℕ) (γ : SmoothForm n X (2 * p)) :
    ∃ N : ℝ, N > 0 ∧ isConePositive (γ + N • kahlerPow p)

/-- **Rational Shift Suffices** (Density of ℚ in ℝ).
    The above also works for rational N, by approximation. -/
axiom shift_makes_conePositive_rat (p : ℕ) (γ : SmoothForm n X (2 * p)) :
    ∃ N : ℚ, N > 0 ∧ isConePositive (γ + (N : ℝ) • kahlerPow p)

end
