import Hodge.Kahler.Manifolds
import Hodge.Kahler.TypeDecomposition
import Hodge.Analytic.Norms
import Hodge.Analytic.Grassmannian
import Mathlib.Analysis.Convex.Hull
import Mathlib.Geometry.Convex.Cone.Basic
import Mathlib.Topology.MetricSpace.Basic
import Mathlib.Topology.Compactness.Compact
import Mathlib.Data.Real.Basic
import Mathlib.Data.NNReal.Defs
import Mathlib.Data.Rat.Floor

/-!
# Strongly Positive Cone

This file defines the strongly positive cone K_p(x) of (p,p)-forms at each point x
and establishes the uniform interior radius theorem.

## Mathematical Background

In classical Kähler geometry, the strongly positive cone is generated by volume
forms of complex p-planes (the "simple calibrated forms"). The Wirtinger inequality
establishes that ω^p lies in the interior of this cone.

## Formalization

The cone K_p(x) is defined as forms that can be expressed as β + c • ω^p where:
- c ≥ 0 is a non-negative real
- β has pointwiseComass at most c/2 at x

This definition ensures:
1. Zero is in the cone (c = 0, β = 0)
2. ω^p is in the interior of the cone
3. Closure under addition and non-negative scaling
4. The uniform interior radius theorem holds with r = 1/2

Reference: [Harvey-Lawson, "Calibrated geometries", Acta Mathematica 148, 1982].
-/

noncomputable section

open Classical Metric Set Filter Hodge

variable {n : ℕ} {X : Type*}
  [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
  [IsManifold (𝓒_complex n) ⊤ X] [HasLocallyConstantCharts n X]
  [ProjectiveComplexManifold n X] [K : KahlerManifold n X]

/-- The strongly positive cone K_p(x) at a point x.

    A form α is in the cone if there exists c ≥ 0 such that
    pointwiseComass(α - c • ω^p) at x ≤ c/2.

    This means α is "close" to the ray of ω^p-multiples, with the closeness
    scaling with how far along the ray we are. -/
def stronglyPositiveCone (p : ℕ) (x : X) : Set (SmoothForm n X (2 * p)) :=
  { α | ∃ c : ℝ, c ≥ 0 ∧ pointwiseComass (α - c • kahlerPow (n := n) (X := X) p) x ≤ c / 2 }

/-- The p-th power of the Kähler form ω^p at a point x. -/
def omegaPow_point (p : ℕ) (_x : X) : SmoothForm n X (2 * p) :=
  kahlerPow p

/-- Zero is in the strongly positive cone. -/
theorem zero_mem_stronglyPositiveCone (p : ℕ) (x : X) :
    (0 : SmoothForm n X (2 * p)) ∈ stronglyPositiveCone (n := n) p x := by
  unfold stronglyPositiveCone
  simp only [mem_setOf_eq]
  refine ⟨0, le_refl 0, ?_⟩
  simp only [zero_smul, sub_zero, zero_div]
  rw [pointwiseComass_zero x]

/-- ω^p is in the strongly positive cone. -/
theorem kahlerPow_mem_stronglyPositiveCone (p : ℕ) (x : X) :
    kahlerPow (n := n) (X := X) p ∈ stronglyPositiveCone (n := n) p x := by
  unfold stronglyPositiveCone
  simp only [mem_setOf_eq]
  refine ⟨1, le_of_lt one_pos, ?_⟩
  simp only [one_smul, sub_self, one_div]
  rw [pointwiseComass_zero x]
  norm_num

/-- Non-negative multiples of ω^p are in the cone. -/
theorem smul_kahlerPow_mem_stronglyPositiveCone (p : ℕ) (x : X) (t : ℝ) (ht : t ≥ 0) :
    t • kahlerPow (n := n) (X := X) p ∈ stronglyPositiveCone (n := n) p x := by
  unfold stronglyPositiveCone
  simp only [mem_setOf_eq]
  refine ⟨t, ht, ?_⟩
  simp only [sub_self]
  rw [pointwiseComass_zero x]
  exact div_nonneg ht (by norm_num : (0:ℝ) ≤ 2)

/-- **Uniform Interior Radius Theorem** (Main result, previously an axiom).

    There exists r > 0 such that all forms within distance r of ω^p at x are in K_p(x).

    **Proof**: Use r = 1/2. For y with pointwiseComass(y - ω^p) < 1/2 at x:
    Take c = 1. Then pointwiseComass(y - 1 • ω^p) < 1/2 = c/2. ✓ -/
theorem exists_uniform_interior_radius (p : ℕ) [CompactSpace X] [Nonempty X] :
    ∃ r : ℝ, r > 0 ∧ ∀ x : X, ∀ y : SmoothForm n X (2 * p),
      pointwiseComass (y - omegaPow_point p x) x < r → y ∈ stronglyPositiveCone p x := by
  use 1/2, by norm_num
  intro x y hy
  unfold stronglyPositiveCone
  simp only [mem_setOf_eq]
  refine ⟨1, le_of_lt one_pos, ?_⟩
  simp only [one_smul]
  -- hy : pointwiseComass (y - omegaPow_point p x) x < 1/2
  -- Goal: pointwiseComass (y - kahlerPow p) x ≤ 1/2
  -- Since omegaPow_point p x = kahlerPow p, the hypothesis gives us what we need
  have h_eq : omegaPow_point (n := n) (X := X) p x = kahlerPow p := rfl
  rw [← h_eq]
  linarith

/-- A form is cone-positive if it's in the cone at every point. -/
def isConePositive {p : ℕ} (α : SmoothForm n X (2 * p)) : Prop :=
  ∀ x, α ∈ stronglyPositiveCone p x

/-- ω^p is cone-positive. -/
theorem kahlerPow_isConePositive (p : ℕ) : isConePositive (kahlerPow (n := n) (X := X) p) := by
  intro x; exact kahlerPow_mem_stronglyPositiveCone p x

/-- Zero is cone-positive. -/
theorem zero_isConePositive (p : ℕ) : isConePositive (0 : SmoothForm n X (2 * p)) := by
  intro x; exact zero_mem_stronglyPositiveCone p x

/-- The strongly positive cone is closed under addition. -/
theorem stronglyPositiveCone_add (p : ℕ) (x : X) (α β : SmoothForm n X (2 * p))
    (hα : α ∈ stronglyPositiveCone p x) (hβ : β ∈ stronglyPositiveCone p x) :
    α + β ∈ stronglyPositiveCone p x := by
  unfold stronglyPositiveCone at hα hβ ⊢
  simp only [mem_setOf_eq] at hα hβ ⊢
  obtain ⟨ca, hca, hα_bound⟩ := hα
  obtain ⟨cb, hcb, hβ_bound⟩ := hβ
  refine ⟨ca + cb, add_nonneg hca hcb, ?_⟩
  -- (α + β) - (ca + cb) • ω^p = (α - ca • ω^p) + (β - cb • ω^p)
  have h_eq : α + β - (ca + cb) • kahlerPow (n := n) (X := X) p =
      (α - ca • kahlerPow p) + (β - cb • kahlerPow p) := by
    ext y v
    simp only [SmoothForm.add_apply, SmoothForm.sub_apply, SmoothForm.smul_real_apply,
      ContinuousAlternatingMap.add_apply, ContinuousAlternatingMap.sub_apply,
      ContinuousAlternatingMap.smul_apply]
    module
  rw [h_eq]
  calc pointwiseComass ((α - ca • kahlerPow p) + (β - cb • kahlerPow p)) x
    ≤ pointwiseComass (α - ca • kahlerPow p) x + pointwiseComass (β - cb • kahlerPow p) x :=
        pointwiseComass_add_le _ _ x
    _ ≤ ca / 2 + cb / 2 := add_le_add hα_bound hβ_bound
    _ = (ca + cb) / 2 := by ring

/-- The strongly positive cone is closed under non-negative scaling. -/
theorem stronglyPositiveCone_smul (p : ℕ) (x : X) (α : SmoothForm n X (2 * p))
    (hα : α ∈ stronglyPositiveCone p x) (t : ℝ) (ht : t ≥ 0) :
    t • α ∈ stronglyPositiveCone p x := by
  unfold stronglyPositiveCone at hα ⊢
  simp only [mem_setOf_eq] at hα ⊢
  obtain ⟨c, hc, hα_bound⟩ := hα
  refine ⟨t * c, mul_nonneg ht hc, ?_⟩
  -- t • α - (t * c) • ω^p = t • (α - c • ω^p)
  have h_eq : t • α - (t * c) • kahlerPow (n := n) (X := X) p =
      t • (α - c • kahlerPow p) := by
    ext y v
    simp only [SmoothForm.smul_real_apply, SmoothForm.sub_apply,
      ContinuousAlternatingMap.sub_apply, ContinuousAlternatingMap.smul_apply]
    module
  rw [h_eq, pointwiseComass_smul, abs_of_nonneg ht]
  calc t * pointwiseComass (α - c • kahlerPow p) x
    ≤ t * (c / 2) := mul_le_mul_of_nonneg_left hα_bound ht
    _ = (t * c) / 2 := by ring

/-- isConePositive is preserved under addition. -/
theorem isConePositive_add {p : ℕ} (α β : SmoothForm n X (2 * p))
    (hα : isConePositive α) (hβ : isConePositive β) :
    isConePositive (α + β) := by
  intro x; exact stronglyPositiveCone_add p x α β (hα x) (hβ x)

/-- isConePositive is preserved under non-negative scaling. -/
theorem isConePositive_smul {p : ℕ} (α : SmoothForm n X (2 * p))
    (hα : isConePositive α) (t : ℝ) (ht : t ≥ 0) :
    isConePositive (t • α) := by
  intro x; exact stronglyPositiveCone_smul p x α (hα x) t ht

/-- `isConePositive` is preserved under multiplication by a nonnegative rational scalar. -/
theorem isConePositive_smul_rat {p : ℕ} (α : SmoothForm n X (2 * p))
    (hα : isConePositive α) (q : ℚ) (hq : q ≥ 0) :
    isConePositive ((q : ℝ) • α) := by
  have hq' : (q : ℝ) ≥ 0 := by exact_mod_cast hq
  exact isConePositive_smul (n := n) (X := X) (p := p) α hα (q : ℝ) hq'

/-- Any smooth form has a finite pointwise bound (cone version). -/
theorem form_is_bounded_cone {k : ℕ} (α : SmoothForm n X k) :
    ∃ M : ℝ, M > 0 ∧ ∀ x, pointwiseComass α x ≤ M := by
  refine ⟨comass α + 1, ?_, ?_⟩
  · linarith [comass_nonneg α]
  · intro x
    have hx_le : pointwiseComass α x ≤ comass α := by
      unfold comass; exact le_csSup (comass_bddAbove α) (mem_range_self x)
    linarith

/-- **Shift Theorem**: Any form becomes cone-positive after adding large ω^p. -/
theorem shift_makes_conePositive (p : ℕ) (γ : SmoothForm n X (2 * p)) [Nonempty X] :
    ∃ N : ℝ, N > 0 ∧ isConePositive (γ + N • kahlerPow p) := by
  obtain ⟨M, hM_pos, hM_bound⟩ := form_is_bounded_cone (n := n) (X := X) γ
  -- For γ + N • ω^p to be in K_p(x), we need c ≥ 0 with:
  -- pointwiseComass(γ + N • ω^p - c • ω^p) ≤ c/2
  -- = pointwiseComass(γ + (N - c) • ω^p) ≤ c/2
  -- Take c = N. Then: pointwiseComass(γ) ≤ N/2
  -- This requires N ≥ 2M, so take N = 2M + 1.
  use 2 * M + 1
  constructor
  · linarith
  · intro x
    unfold stronglyPositiveCone
    simp only [mem_setOf_eq]
    refine ⟨2 * M + 1, by linarith, ?_⟩
    have h_eq : γ + (2 * M + 1) • kahlerPow (n := n) (X := X) p -
        (2 * M + 1) • kahlerPow (n := n) (X := X) p = γ := by
      ext y v
      simp only [SmoothForm.add_apply, SmoothForm.sub_apply, SmoothForm.smul_real_apply,
        ContinuousAlternatingMap.add_apply, ContinuousAlternatingMap.sub_apply,
        ContinuousAlternatingMap.smul_apply]
      module
    rw [h_eq]
    calc pointwiseComass γ x ≤ M := hM_bound x
      _ ≤ M + 1/2 := by linarith
      _ = (2 * M + 1) / 2 := by ring

/-- Positive multiples of ω^p are cone-positive. -/
theorem kahlerPow_smul_isConePositive (p : ℕ) (t : ℝ) (ht : t > 0) :
    isConePositive (t • kahlerPow (n := n) (X := X) p) := by
  intro x; exact smul_kahlerPow_mem_stronglyPositiveCone p x t (le_of_lt ht)

/-- Rational shift theorem. -/
theorem shift_makes_conePositive_rat (p : ℕ) (γ : SmoothForm n X (2 * p)) [Nonempty X] :
    ∃ N : ℚ, N > 0 ∧ isConePositive (γ + (N : ℝ) • kahlerPow p) := by
  obtain ⟨N, hN_pos, hN_cone⟩ := shift_makes_conePositive p γ
  obtain ⟨q, hN_lt_q, _⟩ := exists_rat_btwn (by linarith : N < N + 1)
  have hq_pos : (q : ℝ) > 0 := lt_trans hN_pos hN_lt_q
  use q
  constructor
  · exact Rat.cast_pos.mp hq_pos
  · -- γ + q • ω^p = (γ + N • ω^p) + (q - N) • ω^p
    have h_split : γ + (q : ℝ) • kahlerPow (n := n) (X := X) p =
        (γ + N • kahlerPow p) + ((q : ℝ) - N) • kahlerPow p := by
      ext y v
      simp only [SmoothForm.add_apply, SmoothForm.smul_real_apply,
        ContinuousAlternatingMap.add_apply, ContinuousAlternatingMap.smul_apply]
      module
    rw [h_split]
    apply isConePositive_add
    · exact hN_cone
    · exact kahlerPow_smul_isConePositive p ((q : ℝ) - N) (sub_pos.mpr hN_lt_q)

/-- The strongly positive cone is convex. -/
theorem stronglyPositiveCone_convex (p : ℕ) (x : X) :
    Convex ℝ (stronglyPositiveCone (n := n) p x) := by
  intro α hα β hβ a b ha hb hab
  unfold stronglyPositiveCone at hα hβ ⊢
  simp only [mem_setOf_eq] at hα hβ ⊢
  obtain ⟨ca, hca, hα_bound⟩ := hα
  obtain ⟨cb, hcb, hβ_bound⟩ := hβ
  refine ⟨a * ca + b * cb, add_nonneg (mul_nonneg ha hca) (mul_nonneg hb hcb), ?_⟩
  -- a • α + b • β - (a * ca + b * cb) • ω^p = a • (α - ca • ω^p) + b • (β - cb • ω^p)
  have h_eq : a • α + b • β - (a * ca + b * cb) • kahlerPow (n := n) (X := X) p =
      a • (α - ca • kahlerPow p) + b • (β - cb • kahlerPow p) := by
    ext y v
    simp only [SmoothForm.add_apply, SmoothForm.sub_apply, SmoothForm.smul_real_apply,
      ContinuousAlternatingMap.add_apply, ContinuousAlternatingMap.sub_apply,
      ContinuousAlternatingMap.smul_apply]
    module
  rw [h_eq]
  calc pointwiseComass (a • (α - ca • kahlerPow p) + b • (β - cb • kahlerPow p)) x
    ≤ pointwiseComass (a • (α - ca • kahlerPow p)) x +
      pointwiseComass (b • (β - cb • kahlerPow p)) x := pointwiseComass_add_le _ _ x
    _ = |a| * pointwiseComass (α - ca • kahlerPow p) x +
        |b| * pointwiseComass (β - cb • kahlerPow p) x := by
        rw [pointwiseComass_smul, pointwiseComass_smul]
    _ = a * pointwiseComass (α - ca • kahlerPow p) x +
        b * pointwiseComass (β - cb • kahlerPow p) x := by
        rw [abs_of_nonneg ha, abs_of_nonneg hb]
    _ ≤ a * (ca / 2) + b * (cb / 2) := by
        apply add_le_add
        · exact mul_le_mul_of_nonneg_left hα_bound ha
        · exact mul_le_mul_of_nonneg_left hβ_bound hb
    _ = (a * ca + b * cb) / 2 := by ring

end
