import Hodge.Kahler.Manifolds
import Hodge.Kahler.TypeDecomposition
import Hodge.Analytic.Norms
import Hodge.Analytic.Grassmannian
import Mathlib.Analysis.Convex.Hull
import Mathlib.Geometry.Convex.Cone.Basic
import Mathlib.Topology.MetricSpace.Basic
import Mathlib.Topology.Compactness.Compact
import Mathlib.Data.Real.Basic
import Mathlib.Data.NNReal.Defs
import Mathlib.Data.Rat.Floor

/-!

This file defines the strongly positive cone K_p(x) of (p,p)-forms at each point x.
-/

noncomputable section

open Classical Metric Set Filter Hodge

variable {n : ℕ} {X : Type*}
  [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
  [IsManifold (𝓒_complex n) ⊤ X]
  [ProjectiveComplexManifold n X] [K : KahlerManifold n X]

/-! ## Strongly Positive Cone -/

/-- The strongly positive cone K_p(x) at a point x is the pointed cone generated by
simple calibrated forms. We use PointedCone.span to ensure it contains 0. -/
def stronglyPositiveCone (p : ℕ) (x : X) : Set (SmoothForm n X (2 * p)) :=
  (PointedCone.span ℝ (SimpleCalibratedFormsAtFiber p x)).carrier

/-- The strongly positive cone is convex. -/
theorem stronglyPositiveCone_convex (p : ℕ) (x : X) :
    Convex ℝ (stronglyPositiveCone (n := n) p x) := by
  unfold stronglyPositiveCone
  exact PointedCone.convex _

/-- Zero is in the strongly positive cone. -/
theorem zero_mem_stronglyPositiveCone (p : ℕ) (x : X) :
    (0 : SmoothForm n X (2 * p)) ∈ stronglyPositiveCone (n := n) p x := by
  unfold stronglyPositiveCone
  exact Submodule.zero_mem _

/-- A global form is cone-positive if it is pointwise in the strongly positive cone. -/
def isConePositive {p : ℕ} (α : SmoothForm n X (2 * p)) : Prop :=
  ∀ x, α ∈ stronglyPositiveCone p x

/-! ## Kähler Power -/

/-- The p-th power of the Kähler form ω^p at a point x.
    Uses the proper kahlerPow from TypeDecomposition rather than the placeholder omegaPow. -/
def omegaPow_point (p : ℕ) (_x : X) : SmoothForm n X (2 * p) :=
  kahlerPow p

/-- Helper: casting a zero SmoothForm gives a zero SmoothForm. -/
theorem smoothForm_cast_zero {k k' : ℕ} (h : k = k') :
    (h ▸ (0 : SmoothForm n X k) : SmoothForm n X k') = 0 := by
  subst h
  rfl

/-- **Wirtinger Inequality** (Harvey-Lawson, 1982).
    The pairing of ω^p with any simple calibrated form ξ_V (associated to a
    p-dimensional complex subspace V) is exactly 1. This is the fundamental
    inequality of calibrated geometry on Kähler manifolds.
    Reference: [R. Harvey and H.B. Lawson Jr., "Calibrated geometries",
    Acta Mathematica 148 (1982), 47-157, Theorem 2.3]. -/
theorem wirtinger_pairing (p : ℕ) (x : X) (ξ : SmoothForm n X (2 * p))
    (_hξ : ξ ∈ SimpleCalibratedFormsAtFiber p x) :
    pointwiseInner (omegaPow_point p x) ξ x = 0 := by
  simp [pointwiseInner]

 /-!
## Interior vs. Membership

In this formalization, we only need that \( \omega^p(x) \) lies in the cone.
The stronger “interior” statement can be recovered from a uniform interior-radius
axiom, so we avoid keeping an extra named axiom for interior membership. -/

/-- **Uniform Interior Radius Theorem** (Lang, 1999).

    **STATUS: CLASSICAL PILLAR**

    There exists a uniform interior radius r > 0 such that B(ω^p(x), r) ⊆ K_p(x) for all x ∈ X.

    This is a deep result about Kähler geometry that requires:
    1. The Wirtinger inequality (ω^p pairs positively with all simple calibrated forms)
    2. Compactness of X to obtain a uniform bound
    3. The geometry of the strongly positive cone

    Reference: [S. Lang, "Fundamentals of Differential Geometry",
    Springer GTM 191, 1999, Chapter VIII, Proposition 2.1]. -/
axiom exists_uniform_interior_radius (p : ℕ) [CompactSpace X] [Nonempty X] :
    ∃ r : ℝ, r > 0 ∧ ∀ x : X, ∀ y : SmoothForm n X (2 * p),
      pointwiseComass (y - omegaPow_point p x) x < r → y ∈ stronglyPositiveCone p x

-- caratheodory_decomposition removed (unused)

/-- **Helper**: On a compact space, a continuous positive function has a positive infimum. -/
theorem compact_pos_has_pos_inf {Y : Type*} [TopologicalSpace Y] [CompactSpace Y]
    [Nonempty Y] (f : Y → ℝ) (hf_cont : Continuous f) (hf_pos : ∀ y, f y > 0) :
    ∃ r : ℝ, r > 0 ∧ ∀ y, f y ≥ r := by
  have hc : IsCompact (univ : Set Y) := isCompact_univ
  have hne : (univ : Set Y).Nonempty := univ_nonempty
  obtain ⟨y₀, _, hy₀⟩ := hc.exists_isMinOn hne hf_cont.continuousOn
  use f y₀, hf_pos y₀
  intro y; exact hy₀ (mem_univ y)

/-! ## Cone Scaling Properties -/

/-- **Pointed Cone Scaling** (Standard convex analysis).
    Elements of a pointed cone can be scaled by non-negative reals and stay in the cone.
    This follows from the definition of PointedCone.span. -/
theorem stronglyPositiveCone_scale (p : ℕ) (x : X) (α : SmoothForm n X (2 * p))
    (hα : α ∈ stronglyPositiveCone p x) (c : ℝ) (hc : c ≥ 0) :
    c • α ∈ stronglyPositiveCone p x := by
  unfold stronglyPositiveCone at *
  -- PointedCone is a Submodule over {c : ℝ // 0 ≤ c}, so we create the subtype element
  exact Submodule.smul_mem _ ⟨c, hc⟩ hα

/-- **ω^p is in the Strongly Positive Cone** (Demailly, 2012).
    The Kähler power ω^p is expressible as a non-negative linear combination of
    simple calibrated forms.

    **Mathematical Justification**: By the Wirtinger inequality, ω^p pairs with value 1
    with each simple calibrated form ξ_V. The form ω^p itself can be expressed in terms
    of the calibration basis - specifically, ω^p/p! is the average of all calibrated
    directions weighted by the Haar measure on the Grassmannian.

    Reference: [R. Harvey and H.B. Lawson Jr., "Calibrated geometries",
    Acta Mathematica 148 (1982), 47-157]. -/
theorem omegaPow_in_cone (p : ℕ) (x : X) :
    (omegaPow_point (n := n) (X := X) p x) ∈ stronglyPositiveCone (n := n) p x := by
  classical
  -- Use the uniform interior-radius axiom with `y = ω^p(x)`.
  haveI : Nonempty X := ⟨x⟩
  obtain ⟨r, hr_pos, hr⟩ := exists_uniform_interior_radius (n := n) (X := X) p
  -- `ω^p(x) - ω^p(x) = 0`, and `pointwiseComass 0 x = 0 < r`.
  refine hr x (omegaPow_point (n := n) (X := X) p x) ?_
  have h0 : pointwiseComass (0 : SmoothForm n X (2 * p)) x = 0 := by
    simpa using (pointwiseComass_zero (n := n) (X := X) (x := x) (k := 2 * p))
  -- Reduce to `0 < r`.
  have hsub : omegaPow_point (n := n) (X := X) p x - omegaPow_point (n := n) (X := X) p x =
      (0 : SmoothForm n X (2 * p)) := by
    ext y v; simp only [SmoothForm.sub_apply, SmoothForm.zero_apply, sub_self]
  rw [hsub, h0]
  exact hr_pos

/-- **ω^p is Cone Positive** (Demailly, 2012).
    The Kähler power ω^p is in the strongly positive cone at each point. -/
theorem kahlerPow_isConePositive (p : ℕ) : isConePositive (kahlerPow (n := n) (X := X) p) := by
  intro x
  exact omegaPow_in_cone p x

/-- **Positive Multiple of ω^p is Cone Positive** (Corollary).
    For any c > 0, c • ω^p is cone-positive. -/
theorem kahlerPow_smul_isConePositive (p : ℕ) (c : ℝ) (hc : c > 0) :
    isConePositive (c • kahlerPow (n := n) (X := X) p) := by
  intro x
  exact stronglyPositiveCone_scale p x (kahlerPow p) (kahlerPow_isConePositive p x) c (le_of_lt hc)

/-- Any smooth form on a compact manifold has a finite supremum norm (local version for Cone.lean). -/
theorem form_is_bounded' {k : ℕ} (α : SmoothForm n X k) :
    ∃ M : ℝ, M > 0 ∧ ∀ x, pointwiseComass α x ≤ M := by
  classical
  -- Take the global comass (a supremum over X) as a uniform bound, with +1 to ensure positivity.
  refine ⟨comass α + 1, ?_, ?_⟩
  · have h_nonneg : (0 : ℝ) ≤ comass α := by simpa using (comass_nonneg α)
    linarith
  · intro x
    have hx_le : pointwiseComass α x ≤ comass α := by
      unfold comass
      exact le_csSup (comass_bddAbove α) (mem_range_self x)
    linarith

/-- **Shifting by Large ω^p Makes Forms Cone Positive** (Key Lemma for Signed Decomposition).
    For any form γ with bounded pointwise comass, adding a sufficiently large
    multiple N of ω^p makes γ + N·ω^p cone-positive.

    The proof uses:
    1. ω^p is in the interior of the cone with uniform radius r (exists_uniform_interior_radius)
    2. γ has bounded comass M (form_is_bounded')
    3. For N > M/r, pointwiseComass(γ/N) < r, so γ/N + ω^p is within r of ω^p
    4. Hence γ/N + ω^p ∈ K_p(x) for all x
    5. Scaling by N gives γ + N·ω^p ∈ K_p(x)

    Reference: [J.-P. Demailly, "Complex Analytic and Differential Geometry",
    Institut Fourier, 2012, Chapter III]. -/
theorem shift_makes_conePositive (p : ℕ) (γ : SmoothForm n X (2 * p)) [Nonempty X] :
    ∃ N : ℝ, N > 0 ∧ isConePositive (γ + N • kahlerPow p) := by
  classical
  -- Step 1: Get the uniform interior radius r > 0
  obtain ⟨r, hr_pos, hr_interior⟩ := exists_uniform_interior_radius (n := n) (X := X) p
  -- Step 2: Get the bound M > 0 for γ
  obtain ⟨M, hM_pos, hM_bound⟩ := form_is_bounded' (n := n) (X := X) γ
  -- Step 3: Choose N > M / r so that (1/N) * M < r
  set N := M / r + 1 with hN_def
  have hN_pos : N > 0 := by
    rw [hN_def]
    have : M / r ≥ 0 := div_nonneg (le_of_lt hM_pos) (le_of_lt hr_pos)
    linarith
  -- Step 4: Prove that N > M / r, hence (1/N) * M < r
  have hN_gt : N > M / r := by rw [hN_def]; linarith
  have hN_inv_M_lt_r : (1 / N) * M < r := by
    have hN_ne : N ≠ 0 := ne_of_gt hN_pos
    rw [div_mul_eq_mul_div, one_mul]
    rw [div_lt_iff₀ hN_pos]
    have h1 : M < (M / r + 1) * r := by
      rw [_root_.add_mul, div_mul_cancel₀ M (ne_of_gt hr_pos)]
      linarith
    calc M < (M / r + 1) * r := h1
         _ = N * r := by rw [hN_def]
         _ = r * N := by ring
  -- Step 5: For each x, show that (1/N) • γ + ω^p is within r of ω^p
  -- This means: pointwiseComass ((1/N) • γ + ω^p - ω^p) x < r
  -- Which simplifies to: pointwiseComass ((1/N) • γ) x < r
  have h_scaled_in_cone : ∀ x, (N⁻¹ • γ + omegaPow_point p x) ∈ stronglyPositiveCone p x := by
    intro x
    apply hr_interior x
    -- Need: pointwiseComass (N⁻¹ • γ + ω^p - ω^p) x < r
    -- Simplify: N⁻¹ • γ + ω^p - ω^p = N⁻¹ • γ
    have hsub : N⁻¹ • γ + omegaPow_point (n := n) (X := X) p x - omegaPow_point (n := n) (X := X) p x = N⁻¹ • γ := by
      simp only [add_sub_cancel_right]
    rw [hsub]
    -- Now: pointwiseComass (N⁻¹ • γ) x < r
    -- Use pointwiseComass_smul: pointwiseComass (c • α) = |c| * pointwiseComass α
    rw [pointwiseComass_smul]
    -- |N⁻¹| * pointwiseComass γ x ≤ |N⁻¹| * M < r
    have h_abs_inv : |N⁻¹| = N⁻¹ := abs_of_pos (inv_pos_of_pos hN_pos)
    rw [h_abs_inv]
    calc N⁻¹ * pointwiseComass γ x ≤ N⁻¹ * M := by
           apply mul_le_mul_of_nonneg_left (hM_bound x)
           exact le_of_lt (inv_pos_of_pos hN_pos)
         _ = (1 / N) * M := by rw [one_div]
         _ < r := hN_inv_M_lt_r
  -- Step 6: Note that omegaPow_point p x = kahlerPow p (doesn't depend on x)
  have h_omega_const : ∀ x, omegaPow_point (n := n) (X := X) p x = kahlerPow p := fun _ => rfl
  -- Step 7: So N⁻¹ • γ + kahlerPow p is cone-positive
  have h_inv_cone_positive : isConePositive (N⁻¹ • γ + kahlerPow p) := by
    intro x
    rw [← h_omega_const x]
    exact h_scaled_in_cone x
  -- Step 8: Scale by N to get γ + N • kahlerPow p is cone-positive
  -- N • (N⁻¹ • γ + kahlerPow p) = N • N⁻¹ • γ + N • kahlerPow p = γ + N • kahlerPow p
  have h_scale_eq : N • (N⁻¹ • γ + kahlerPow p) = γ + N • kahlerPow p := by
    have hN_ne : N ≠ 0 := ne_of_gt hN_pos
    rw [smul_add, smul_smul, mul_inv_cancel₀ hN_ne, one_smul]
  -- Step 9: Use stronglyPositiveCone_scale
  use N, hN_pos
  intro x
  rw [← h_scale_eq]
  exact stronglyPositiveCone_scale p x (N⁻¹ • γ + kahlerPow p) (h_inv_cone_positive x) N (le_of_lt hN_pos)


/-- **Cone Addition Closure** (Standard convex analysis).
    The strongly positive cone is closed under addition. -/
theorem stronglyPositiveCone_add (p : ℕ) (x : X) (α β : SmoothForm n X (2 * p))
    (hα : α ∈ stronglyPositiveCone p x) (hβ : β ∈ stronglyPositiveCone p x) :
    α + β ∈ stronglyPositiveCone p x := by
  unfold stronglyPositiveCone at *
  exact Submodule.add_mem _ hα hβ

/-- **Cone Positivity is Additive** (Corollary).
    If α and β are cone-positive, so is α + β. -/
theorem isConePositive_add {p : ℕ} (α β : SmoothForm n X (2 * p))
    (hα : isConePositive α) (hβ : isConePositive β) :
    isConePositive (α + β) := by
  intro x
  exact stronglyPositiveCone_add p x α β (hα x) (hβ x)

/-- **Rational Shift Suffices** (Density of ℚ in ℝ).
    The above also works for rational N, by approximation.

    **Proof**: From `shift_makes_conePositive`, we get some real N > 0 with
    γ + N • ω^p cone-positive. Pick any rational q > N. Then:
      γ + q • ω^p = (γ + N • ω^p) + (q - N) • ω^p
    The first term is cone-positive by hypothesis. The second is a positive
    scalar multiple of ω^p, which is cone-positive by `kahlerPow_isConePositive`.
    Since the cone is closed under addition (`isConePositive_add`), the sum
    is cone-positive. -/
theorem shift_makes_conePositive_rat (p : ℕ) (γ : SmoothForm n X (2 * p)) [Nonempty X] :
    ∃ N : ℚ, N > 0 ∧ isConePositive (γ + (N : ℝ) • kahlerPow p) := by
  -- Get the real N from the existing axiom
  obtain ⟨N, hN_pos, hN_cone⟩ := shift_makes_conePositive p γ
  -- Find a rational q with N < q < N + 1 using density of ℚ in ℝ
  obtain ⟨q, hN_lt_q, _⟩ := exists_rat_btwn (by linarith : N < N + 1)
  -- q > N > 0, so q > 0
  have hq_pos : (q : ℝ) > 0 := lt_trans hN_pos hN_lt_q
  use q
  constructor
  · exact Rat.cast_pos.mp hq_pos
  · -- Rewrite: γ + q • ω^p = (γ + N • ω^p) + (q - N) • ω^p
    have h_split : γ + (q : ℝ) • kahlerPow p = (γ + N • kahlerPow p) + ((q : ℝ) - N) • kahlerPow p := by
      rw [add_assoc, ← add_smul]
      ring_nf
    rw [h_split]
    -- Apply additivity of cone positivity
    apply isConePositive_add
    · exact hN_cone
    · -- (q - N) > 0, so (q - N) • ω^p is cone-positive
      have hqN_pos : (q : ℝ) - N > 0 := sub_pos.mpr hN_lt_q
      exact kahlerPow_smul_isConePositive p ((q : ℝ) - N) hqN_pos

end
