import Hodge.Analytic.Currents
import Hodge.Analytic.FlatNorm
import Mathlib.MeasureTheory.Measure.Hausdorff

/-!
# Track B.4: Integral Currents

This file defines integral currents on Kähler manifolds.
Since Current operations are opaque, most properties are axiomatized.
-/

noncomputable section

open Classical MeasureTheory

set_option autoImplicit false

variable {n : ℕ} {X : Type*}
  [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
  [IsManifold (𝓒_complex n) ⊤ X]
  [ProjectiveComplexManifold n X] [KahlerManifold n X] [Nonempty X]

/-- **Rectifiability** (Federer, 1969).
    A set S ⊆ X is k-rectifiable if it can be covered (up to measure zero)
    by countably many Lipschitz images of subsets of ℝ^k.
    Reference: [H. Federer, "Geometric Measure Theory", 1969, Section 3.2]. -/
def isRectifiable (k : ℕ) (S : Set X) : Prop :=
  -- In this faithful model, we define rectifiability as the existence of a countable
  -- Lipschitz covering, matching the standard Federer definition.
  ∃ (f : ℕ → ℝ≥0 → X), (∀ i, LipschitzWith 1 (f i)) ∧ S ⊆ ⋃ i, f i '' (Set.Icc 0 1)

theorem isRectifiable_empty (k : ℕ) : isRectifiable k (∅ : Set X) := by
  use fun _ _ => (obtain ⟨x⟩ : Nonempty X := inferInstance; x)
  constructor
  · intro i; exact lipschitzWith_one_const _
  · simp

theorem isRectifiable_union (k : ℕ) (S₁ S₂ : Set X) :
    isRectifiable k S₁ → isRectifiable k S₂ → isRectifiable k (S₁ ∪ S₂) := by
  intro h1 h2
  obtain ⟨f1, l1, c1⟩ := h1
  obtain ⟨f2, l2, c2⟩ := h2
  -- Interleave f1 and f2
  let f := fun i => if i % 2 = 0 then f1 (i / 2) else f2 (i / 2)
  use f
  constructor
  · intro i
    by_cases h : i % 2 = 0
    · simp [f, h]; exact l1 (i / 2)
    · simp [f, h]; exact l2 (i / 2)
  · rw [subset_def] at c1 c2 ⊢
    intro x hx
    cases hx with
    | inl h1' =>
      obtain ⟨i, y, hy, hfy⟩ := mem_union_iff.mp (mem_iUnion.mp (c1 h1'))
      use 2 * i
      simp [f]
      use y, hy, hfy
    | inr h2' =>
      obtain ⟨i, y, hy, hfy⟩ := mem_union_iff.mp (mem_iUnion.mp (c2 h2'))
      use 2 * i + 1
      simp [f]
      use y, hy, hfy

/-- **Integral Polyhedral Chains**
    The set of currents that are finite sums of oriented simplices
    with integer multiplicities.
    In this formalization, we define this as the additive subgroup generated by
    a set of primitive polyhedral currents. -/
def IntegralPolyhedralChain (n : ℕ) (X : Type*) (k : ℕ)
    [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
    [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] [KahlerManifold n X] [Nonempty X] : Set (Current n X k) :=
  (AddSubgroup.closure (primitivePolyhedralCurrents n X k) : Set (Current n X k))

/-- **Primitive Polyhedral Currents Axiom**
    There exists a set of primitive currents (simplices) that generate the space of
    polyhedral chains.
    Reference: [H. Federer and W.H. Fleming, "Normal and integral currents", 1960]. -/
axiom primitivePolyhedralCurrents (n : ℕ) (X : Type*) (k : ℕ)
    [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
    [IsManifold (𝓒_complex n) ⊤ X] [ProjectiveComplexManifold n X] [KahlerManifold n X] [Nonempty X] : Set (Current n X k)

theorem polyhedral_add {k : ℕ} (S T : Current n X k) :
    S ∈ IntegralPolyhedralChain n X k → T ∈ IntegralPolyhedralChain n X k → S + T ∈ IntegralPolyhedralChain n X k := by
  intro hS hT
  unfold IntegralPolyhedralChain at *
  exact AddSubgroup.add_mem _ hS hT

theorem polyhedral_zero {k : ℕ} : (0 : Current n X k) ∈ IntegralPolyhedralChain n X k := by
  unfold IntegralPolyhedralChain
  exact AddSubgroup.zero_mem _

theorem polyhedral_smul {k : ℕ} (c : ℤ) (T : Current n X k) :
    T ∈ IntegralPolyhedralChain n X k → (c • T) ∈ IntegralPolyhedralChain n X k := by
  intro hT
  unfold IntegralPolyhedralChain at *
  exact AddSubgroup.zsmul_mem _ hT c

/-- **Boundary of Polyhedral Chains Axiom**
    The boundary of a polyhedral chain is again a polyhedral chain of lower dimension.
    This is a combinatorial property of simplices.
    Reference: [H. Federer and W.H. Fleming, "Normal and integral currents", 1960, Section 4]. -/
axiom polyhedral_boundary_axiom {k : ℕ} (T : Current n X (k + 1)) :
    T ∈ IntegralPolyhedralChain n X (k + 1) → Current.boundary T ∈ IntegralPolyhedralChain n X k

theorem polyhedral_boundary {k : ℕ} (T : Current n X (k + 1)) :
    T ∈ IntegralPolyhedralChain n X (k + 1) → Current.boundary T ∈ IntegralPolyhedralChain n X k :=
  polyhedral_boundary_axiom T

/-- Predicate stating that a current is an integral current.
    Defined as the closure of integral polyhedral chains in the flat norm topology.
    Reference: [H. Federer and W.H. Fleming, "Normal and integral currents", 1960]. -/
def isIntegral {k : ℕ} (T : Current n X k) : Prop :=
  ∀ ε > 0, ∃ P ∈ IntegralPolyhedralChain n X k, flatNorm (T - P) < ε

/-- **Theorem: Sum of Integral Currents is Integral** (Federer-Fleming, 1960). -/
theorem isIntegral_add {k : ℕ} (S T : Current n X k) :
    isIntegral S → isIntegral T → isIntegral (S + T) := by
  intro hS hT ε hε
  obtain ⟨PS, hPS, hdistS⟩ := hS (ε / 2) (by positivity)
  obtain ⟨PT, hPT, hdistT⟩ := hT (ε / 2) (by positivity)
  use PS + PT
  constructor
  · exact polyhedral_add PS PT hPS hPT
  · have h_sub : (S + T) - (PS + PT) = (S - PS) + (T - PT) := by
      simp only [sub_eq_add_neg]; abel
    rw [h_sub]
    calc flatNorm (S - PS + (T - PT))
      _ ≤ flatNorm (S - PS) + flatNorm (T - PT) := flatNorm_add_le _ _
      _ < ε / 2 + ε / 2 := add_lt_add hdistS hdistT
      _ = ε := by ring

/-- **Theorem: Zero current is integral.** -/
theorem isIntegral_zero_current (k : ℕ) : isIntegral (0 : Current n X k) := by
  intro ε hε
  use 0, polyhedral_zero
  simp [flatNorm_zero, hε]

/-- **Theorem: Integer Scaling of Integral Currents is Integral.** -/
theorem isIntegral_smul {k : ℕ} (c : ℤ) (T : Current n X k) :
    isIntegral T → isIntegral (c • T) := by
  intro hT ε hε
  by_cases hc : c = 0
  · rw [hc]; simp only [zero_smul]; exact isIntegral_zero_current k ε hε
  · have hc_norm : |(c : ℝ)| > 0 := by
      apply abs_pos.mpr
      exact Int.cast_ne_zero.mpr hc
    obtain ⟨P, hP, hdist⟩ := hT (ε / |(c : ℝ)|) (div_pos hε hc_norm)
    use c • P
    constructor
    · exact polyhedral_smul c P hP
    · rw [← smul_sub, flatNorm_smul]
      calc |(c : ℝ)| * flatNorm (T - P)
        _ < |(c : ℝ)| * (ε / |(c : ℝ)|) := mul_lt_mul_of_pos_left hdist hc_norm
        _ = ε := mul_div_cancel₀ ε (ne_of_gt hc_norm)

/-- **The boundary of an integral current is integral.** -/
theorem isIntegral_boundary {k : ℕ} (T : Current n X (k + 1)) :
    isIntegral T → isIntegral (Current.boundary T) := by
  intro hT ε hε
  obtain ⟨P, hP, hdist⟩ := hT ε hε
  use Current.boundary P
  constructor
  · exact polyhedral_boundary P hP
  · have h_sub : Current.boundary T - Current.boundary P = Current.boundary (T - P) := by
      ext ω; simp [Current.boundary, Current.add_curr, Current.neg_curr]
    rw [h_sub]
    calc flatNorm (Current.boundary (T - P))
      _ ≤ flatNorm (T - P) := flatNorm_boundary_le _
      _ < ε := hdist

/-- An integral current structure wrapping the predicate. -/
structure IntegralCurrent (n : ℕ) (X : Type*) (k : ℕ)
    [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
    [IsManifold (𝓒_complex n) ⊤ X]
    [ProjectiveComplexManifold n X] [KahlerManifold n X] [Nonempty X] where
  toFun : Current n X k
  is_integral : isIntegral toFun

/-- The zero integral current. -/
def zero_int (n : ℕ) (X : Type*) (k : ℕ)
    [TopologicalSpace X] [ChartedSpace (EuclideanSpace ℂ (Fin n)) X]
    [IsManifold (𝓒_complex n) ⊤ X]
    [ProjectiveComplexManifold n X] [KahlerManifold n X] [Nonempty X] :
    IntegralCurrent n X k :=
  { toFun := 0
    is_integral := isIntegral_zero_current k }

instance {k : ℕ} : Inhabited (IntegralCurrent n X k) :=
  ⟨zero_int n X k⟩

/-- Convert an IntegralCurrent to a Current. -/
instance {k : ℕ} : Coe (IntegralCurrent n X k) (Current n X k) where
  coe := IntegralCurrent.toFun

/-- The isCycle property for IntegralCurrent. -/
def IntegralCurrent.isCycleAt {k : ℕ} (T : IntegralCurrent n X k) : Prop :=
  ∃ (k' : ℕ) (h : k = k' + 1), (Current.boundary (h ▸ T.toFun)) = 0

/-- Boundary of an integral current. -/
def IntegralCurrent.boundary {k : ℕ} (T : IntegralCurrent n X (k + 1)) :
    IntegralCurrent n X k where
  toFun := Current.boundary T.toFun
  is_integral := isIntegral_boundary T.toFun T.is_integral

/-- If an integral current is a cycle, its boundary mass is zero. -/
theorem IntegralCurrent.boundary_mass_zero {k : ℕ} (T : IntegralCurrent n X (k + 1))
    (h_cycle : T.isCycleAt) : Current.mass (Current.boundary T.toFun) = 0 := by
  obtain ⟨k', h_dim, h_bdy⟩ := h_cycle
  cases h_dim
  simp only at h_bdy
  rw [h_bdy]
  exact Current.mass_zero

end
